{
    "exceptional-master/setup.py": {},
    "exceptional-master/test_exceptional.py": {
        "test_suppress_repr": {
            "name": "test_suppress_repr",
            "location": 7,
            "return": [
                "None"
            ],
            "arguments": {}
        },
        "test_suppress_context_manager": {
            "name": "test_suppress_context_manager",
            "location": 13,
            "return": [
                "NoReturn"
            ],
            "arguments": {}
        },
        "test_suppress_decorator": {
            "name": "test_suppress_decorator",
            "location": 29,
            "return": [
                "NoReturn"
            ],
            "arguments": {}
        },
        "test_collector_context_manager": {
            "name": "test_collector_context_manager",
            "location": 46,
            "return": [
                "NoReturn"
            ],
            "arguments": {}
        },
        "test_collector_repr": {
            "name": "test_collector_repr",
            "location": 65,
            "return": [
                "None"
            ],
            "arguments": {}
        },
        "test_wrap": {
            "name": "test_wrap",
            "location": 83,
            "return": [
                "NoReturn"
            ],
            "arguments": {}
        },
        "test_wrap_no_exception": {
            "name": "test_wrap_no_exception",
            "location": 89,
            "return": [
                "None"
            ],
            "arguments": {}
        },
        "test_wrap_not_handled": {
            "name": "test_wrap_not_handled",
            "location": 94,
            "return": [
                "NoReturn"
            ],
            "arguments": {}
        },
        "test_wrap_multiple_exceptions": {
            "name": "test_wrap_multiple_exceptions",
            "location": 100,
            "return": [
                "NoReturn"
            ],
            "arguments": {}
        },
        "test_wrap_multiple_exceptions_mapping": {
            "name": "test_wrap_multiple_exceptions_mapping",
            "location": 110,
            "return": [
                "NoReturn"
            ],
            "arguments": {}
        },
        "test_wrap_message_propagated_by_default": {
            "name": "test_wrap_message_propagated_by_default",
            "location": 132,
            "return": [
                "NoReturn"
            ],
            "arguments": {}
        },
        "test_wrap_message": {
            "name": "test_wrap_message",
            "location": 142,
            "return": [
                "NoReturn"
            ],
            "arguments": {}
        },
        "test_wrap_empty_message": {
            "name": "test_wrap_empty_message",
            "location": 149,
            "return": [
                "NoReturn"
            ],
            "arguments": {}
        },
        "test_wrap_message_prefix": {
            "name": "test_wrap_message_prefix",
            "location": 160,
            "return": [
                "NoReturn"
            ],
            "arguments": {}
        },
        "test_wrap_message_format": {
            "name": "test_wrap_message_format",
            "location": 172,
            "return": [
                "NoReturn"
            ],
            "arguments": {}
        },
        "test_wrap_cause": {
            "name": "test_wrap_cause",
            "location": 179,
            "return": [
                "NoReturn"
            ],
            "arguments": {}
        },
        "test_wrap_context": {
            "name": "test_wrap_context",
            "location": 192,
            "return": [
                "NoReturn"
            ],
            "arguments": {}
        },
        "test_wrap_repr": {
            "name": "test_wrap_repr",
            "location": 207,
            "return": [
                "None"
            ],
            "arguments": {}
        },
        "test_wrap_decorator": {
            "name": "test_wrap_decorator",
            "location": 223,
            "return": [
                "None"
            ],
            "arguments": {}
        },
        "test_wrap_invalid_usage": {
            "name": "test_wrap_invalid_usage",
            "location": 232,
            "return": [
                "None"
            ],
            "arguments": {}
        },
        "test_raiser_no_args": {
            "name": "test_raiser_no_args",
            "location": 252,
            "return": [
                "None"
            ],
            "arguments": {}
        },
        "test_raiser_args": {
            "name": "test_raiser_args",
            "location": 258,
            "return": [
                "None"
            ],
            "arguments": {}
        },
        "test_raiser_repr": {
            "name": "test_raiser_repr",
            "location": 272,
            "return": [
                "None"
            ],
            "arguments": {}
        },
        "test_missing_arg_repr": {
            "name": "test_missing_arg_repr",
            "location": 280,
            "return": [
                "None"
            ],
            "arguments": {}
        },
        "test_suppress_decorator.a": {
            "name": "a",
            "location": 31,
            "return": [],
            "arguments": {}
        },
        "test_suppress_decorator.b": {
            "name": "b",
            "location": 35,
            "return": [],
            "arguments": {}
        },
        "test_wrap_decorator.a": {
            "name": "a",
            "location": 225,
            "return": [],
            "arguments": {}
        }
    },
    "exceptional-master/doc/conf.py": {},
    "exceptional-master/src/exceptional/exceptional.py": {
        "escape_format_string": {
            "name": "escape_format_string",
            "location": 9,
            "return": [
                "Any"
            ],
            "arguments": {
                "s": []
            }
        },
        "is_exception_class": {
            "name": "is_exception_class",
            "location": 13,
            "return": [
                "bool"
            ],
            "arguments": {
                "x": []
            }
        },
        "is_multiple_exception_classes": {
            "name": "is_multiple_exception_classes",
            "location": 17,
            "return": [
                "bool"
            ],
            "arguments": {
                "x": []
            }
        },
        "suppress": {
            "name": "suppress",
            "location": 42,
            "return": [
                "ExceptionSuppressor"
            ],
            "arguments": {}
        },
        "collect": {
            "name": "collect",
            "location": 71,
            "return": [
                "ExceptionCollector"
            ],
            "arguments": {}
        },
        "wrap": {
            "name": "wrap",
            "location": 142,
            "return": [
                "Any"
            ],
            "arguments": {
                "original_or_mapping": [],
                "replacement": []
            }
        },
        "raiser": {
            "name": "raiser",
            "location": 287,
            "return": [
                "ExceptionRaiser"
            ],
            "arguments": {
                "exception": []
            }
        },
        "Missing.__repr__": {
            "name": "__repr__",
            "location": 24,
            "return": [
                "str"
            ],
            "arguments": {
                "self": []
            }
        },
        "ExceptionSuppressor.__init__": {
            "name": "__init__",
            "location": 52,
            "return": [
                "None"
            ],
            "arguments": {
                "self": []
            }
        },
        "ExceptionSuppressor.__enter__": {
            "name": "__enter__",
            "location": 55,
            "return": [
                "None"
            ],
            "arguments": {
                "self": []
            }
        },
        "ExceptionSuppressor.__exit__": {
            "name": "__exit__",
            "location": 58,
            "return": [
                "bool"
            ],
            "arguments": {
                "self": [],
                "exc_type": [
                    "Optional[Type[BaseException]]"
                ],
                "exc_value": [
                    "Optional[BaseException]"
                ],
                "exc_traceback": []
            }
        },
        "ExceptionSuppressor.__repr__": {
            "name": "__repr__",
            "location": 66,
            "return": [
                "str"
            ],
            "arguments": {
                "self": []
            }
        },
        "ExceptionCollector.__init__": {
            "name": "__init__",
            "location": 86,
            "return": [
                "None"
            ],
            "arguments": {
                "self": []
            }
        },
        "ExceptionCollector.__enter__": {
            "name": "__enter__",
            "location": 90,
            "return": [
                "_TExceptionCollector@@ExceptionCollector@@"
            ],
            "arguments": {
                "self": [
                    "_TExceptionCollector@@ExceptionCollector@@"
                ]
            }
        },
        "ExceptionCollector.__exit__": {
            "name": "__exit__",
            "location": 93,
            "return": [
                "bool"
            ],
            "arguments": {
                "self": [],
                "exc_type": [
                    "Optional[Type[BaseException]]"
                ],
                "exc_value": [
                    "Optional[BaseException]"
                ],
                "exc_traceback": []
            }
        },
        "ExceptionCollector.__repr__": {
            "name": "__repr__",
            "location": 107,
            "return": [
                "str"
            ],
            "arguments": {
                "self": []
            }
        },
        "ExceptionCollector.__iter__": {
            "name": "__iter__",
            "location": 111,
            "return": [
                "Generator[(nothing, Any, None)]"
            ],
            "arguments": {
                "self": []
            }
        },
        "ExceptionWrapper.__init__": {
            "name": "__init__",
            "location": 218,
            "return": [
                "None"
            ],
            "arguments": {
                "self": []
            }
        },
        "ExceptionWrapper.__enter__": {
            "name": "__enter__",
            "location": 231,
            "return": [
                "_TExceptionWrapper@@ExceptionWrapper@@"
            ],
            "arguments": {
                "self": [
                    "_TExceptionWrapper@@ExceptionWrapper@@"
                ]
            }
        },
        "ExceptionWrapper.__exit__": {
            "name": "__exit__",
            "location": 234,
            "return": [
                "bool"
            ],
            "arguments": {
                "self": [],
                "exc_type": [
                    "Optional[Type[BaseException]]"
                ],
                "exc_value": [
                    "Optional[BaseException]"
                ],
                "exc_traceback": []
            }
        },
        "ExceptionWrapper._find_replacement_exception_class": {
            "name": "_find_replacement_exception_class",
            "location": 259,
            "return": [
                "Optional[Type[BaseException]]"
            ],
            "arguments": {
                "self": [],
                "exception_class": []
            }
        },
        "ExceptionWrapper.__repr__": {
            "name": "__repr__",
            "location": 270,
            "return": [
                "str"
            ],
            "arguments": {
                "self": []
            }
        },
        "ExceptionRaiser.__init__": {
            "name": "__init__",
            "location": 305,
            "return": [
                "None"
            ],
            "arguments": {
                "self": [],
                "exception_class": [],
                "exception_args": [],
                "exception_kwargs": []
            }
        },
        "ExceptionRaiser.__call__": {
            "name": "__call__",
            "location": 315,
            "return": [
                "NoReturn"
            ],
            "arguments": {
                "self": []
            }
        },
        "ExceptionRaiser.__repr__": {
            "name": "__repr__",
            "location": 321,
            "return": [
                "str"
            ],
            "arguments": {
                "self": []
            }
        }
    },
    "exceptional-master/src/exceptional/__init__.py": {}
}